### ISSUE TITLE
Usage on multiple windows

### ISSUE THREAD

**Issue by mattberg** [appcelerator-archive/ti.flurry#27]
I have an app using the classic CommonJS structure, not Alloy. How do you handle using the module on multiple Windows. Once it is initialized in app.js, on subsequent windows, is it possible to just include var Flurry = require('ti.flurry'), or do I need to put global event listeners in app.js and fire them from the windows to call Flurry?

**Comment by hansemannn** [comment]
Likely not an open question anymore, but it's solved via general JS concepts by using a shared object / singleton architecture.
